### ISSUE TITLE
Installing v0.5.0 gives error about unexpected hash

### ISSUE THREAD

**Issue by CodeBleu** [apache/cloudstack-terraform-provider#109]
```
│ Error: Failed to install provider
│
│ Error while installing cloudstack/cloudstack v0.5.0: checksum list has unexpected SHA-256 hash af68c90c16b98d249ad01b9215e0dbcb66cb9de21cb3f977cc73b78d80a90413 (expected 34ace84ac91a9fac1deb1d9ecef12d9478e3b46fd925f6df6811577964cbfcfe)
```

The 0.5.0-pre gives this:
```

- Installing cloudstack/cloudstack v0.5.0-pre...
- Installed cloudstack/cloudstack v0.5.0-pre. Signature validation was skipped due to the registry not containing GPG keys for 
```

**Comment by rohityadavcloud** [comment]
This is known issue, I’ve logged support ticket with Terraform support. You may use this one for now https://registry.terraform.io/providers/shapeblue/cloudstack/latest until the registry issue is resolved.

**Comment by rohityadavcloud** [comment]
@CodeBleu I tested the pre version too and it succeeds for me:
```
ubuntu@backup-nas:~/a$ terraform  init

Initializing the backend...

Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching "0.5.0-pre"...
- Installing cloudstack/cloudstack v0.5.0-pre...
- Installed cloudstack/cloudstack v0.5.0-pre (self-signed, key ID 484248210EE3D884)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

```

**Comment by rohityadavcloud** [comment]
@CodeBleu I've documented the local install method from Github Releases:
https://github.com/apache/cloudstack-terraform-provider/tree/main?tab=readme-ov-file#installing-from-github-release
https://github.com/apache/cloudstack-terraform-provider/wiki#installing-from-github-release

**Comment by CodeBleu** [comment]
@kiranchavala @rohityadavcloud  you can see in my original post here, that I did use the pre version.  Yes, it did install,  but still complains about signature validation was skipped.

**Comment by rohityadavcloud** [comment]
@CodeBleu which terraform version and OS are you using? I got this on a Ubuntu x86_64 VM:
```
ubuntu@backup-nas:~/a$ terraform  init

Initializing the backend...

Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching "0.5.0-pre"...
- Installing cloudstack/cloudstack v0.5.0-pre...
- Installed cloudstack/cloudstack v0.5.0-pre (self-signed, key ID 484248210EE3D884)
```
 
I have Terraform v1.7.5

**Comment by kiranchavala** [comment]
@CodeBleu 

can you remove the exisiting hidden  .terraform folder and  .terraform.lock.hcl files and try again

**Comment by CodeBleu** [comment]
> @CodeBleu which terraform version and OS are you using? I got this on a Ubuntu x86_64 VM:
> 
> ```
> ubuntu@backup-nas:~/a$ terraform  init
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Finding cloudstack/cloudstack versions matching "0.5.0-pre"...
> - Installing cloudstack/cloudstack v0.5.0-pre...
> - Installed cloudstack/cloudstack v0.5.0-pre (self-signed, key ID 484248210EE3D884)
> ```
> 
> I have Terraform v1.7.5

I'm using Tofu v1.6.2 on Ubuntu 22.04

**Comment by CodeBleu** [comment]
> @CodeBleu
> 
> can you remove the exisiting hidden .terraform folder and .terraform.lock.hcl files and try again

This was done prior to opening my issue here.

I believe the issue is with the GPG key not properly being listed in the Terraform registry.  @rohityadavcloud  Maybe because you are the one that created this? and that is why you are seeing a "self-signed" key on yours?

> This can happen if the provider is developed and distributed by a third party or if it's a pre-release version that hasn't been officially signed yet

**Comment by kiranchavala** [comment]
@CodeBleu  @rohityadavcloud 

I think the issue is occurring if both tofu and terraform binaries are present in the same machine




Can you try with only the tofu binary 

```
tofu init
tofu apply 
```

I had no issue when i used tofu   but hitting the issue when I use terraform init

```
root@ubuntu22:~/cloudstack-terraform# tofu --version
OpenTofu v1.6.2

```
```

root@ubuntu22:~/cloudstack-terraform# tofu init

Initializing the backend...

Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching "0.5.0-pre"...
- Installing cloudstack/cloudstack v0.5.0-pre...
- Installed cloudstack/cloudstack v0.5.0-pre. Signature validation was skipped due to the registry not containing GPG keys for this provider

OpenTofu has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that OpenTofu can guarantee to make the same selections by default when
you run "tofu init" in the future.

OpenTofu has been successfully initialized!

You may now begin working with OpenTofu. Try running "tofu plan" to see
any changes that are required for your infrastructure. All OpenTofu commands
should now work.

If you ever set or change modules or backend configuration for OpenTofu,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

```
root@ubuntu22:~/cloudstack-terraform# terraform version
Terraform v1.8.0
```


```
root@ubuntu22:~/cloudstack-terraform# terraform init

Initializing the backend...

Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching "0.5.0-pre"...
- Finding latest version of registry.opentofu.org/cloudstack/cloudstack...
- Installing cloudstack/cloudstack v0.5.0-pre...
- Installed cloudstack/cloudstack v0.5.0-pre (self-signed, key ID 484248210EE3D884)
- Installing registry.opentofu.org/cloudstack/cloudstack v0.5.0...

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│
│ Error while installing registry.opentofu.org/cloudstack/cloudstack v0.5.0: checksum list has unexpected SHA-256 hash
│ af68c90c16b98d249ad01b9215e0dbcb66cb9de21cb3f977cc73b78d80a90413 (expected
│ 34ace84ac91a9fac1deb1d9ecef12d9478e3b46fd925f6df6811577964cbfcfe)
╵
```

**Comment by CodeBleu** [comment]
@kiranchavala 
I'm only using Tofu and Terraform is not installed

There are actually 2 issues here. You can see both of these in your output:
1. Is the checksum issue when it tries to install the NON pre release ( v0.5.0)
2. The other issue is with the pre release (v0.5.0-pre) that is giving a warning about "signature validation was skipped"

**Comment by CodeBleu** [comment]
@rohityadavcloud @kiranchavala I see [this](https://github.com/apache/cloudstack-terraform-provider/pull/108/files) has been approved, but not merged yet.  I'm wondering if merging this and making sure what is put on the Terraform registry is also using the `512` instead of `256` would resolve the issue with :

 `v0.5.0: checksum list has unexpected SHA-256 hash`
 
 Also, I'm not sure of the process with Terraform registry, but when I added a provider to Tofu Registry, I had to bump the version so it would pick up the changes from my github release section and run the pipeline needed to add it to their registry.

**Comment by Ye-Min-Tun** [comment]
I also got the same issue. I installed only terraform (no tofu is used).
I tried to remove both .terraform and .terraform .locak.hcl, but didn't resolve.

**Comment by rohityadavcloud** [comment]
@Ye-Min-Tun thanks for checking. We’ve an open support ticket with hashicorp/terraform support. 

Pl use this method instead in the meanwhile https://github.com/apache/cloudstack-terraform-provider/wiki#installing-from-github-release

**Comment by rohityadavcloud** [comment]
@CodeBleu @Ye-Min-Tun @kiranchavala after some help from the Terraform registry support, I got the release removed and republished the artefacts again. With `Terraform v1.8.0` I was able to make init the provider with no errors:

```
> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching "0.5.0"...
- Installing cloudstack/cloudstack v0.5.0...
- Installed cloudstack/cloudstack v0.5.0 (self-signed, key ID 484248210EE3D884)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Closing on this remark, please test if you still face any issues kindly reopen the issue.

**Comment by CodeBleu** [comment]
@rohityadavcloud This is still not working.  I removed my .terraform directory and .terraform.lock.hcl file and ran the 'init --upgrade' and still get the same error.

```
Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching ">= 0.5.0-pre"...
- Finding hashicorp/aws versions matching ">= 5.43.0"...
- Installing cloudstack/cloudstack v0.5.0...
- Installing hashicorp/aws v5.45.0...
- Installed hashicorp/aws v5.45.0 (signed, key ID 0C0AF313E5FD9F80)

Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://opentofu.org/docs/cli/plugins/signing/
╷
│ Error: Failed to install provider
│
│ Error while installing cloudstack/cloudstack v0.5.0: checksum list has unexpected SHA-256 hash af68c90c16b98d249ad01b9215e0dbcb66cb9de21cb3f977cc73b78d80a90413 (expected 34ace84ac91a9fac1deb1d9ecef12d9478e3b46fd925f6df6811577964cbfcfe)
╵
```

**Comment by rohityadavcloud** [comment]
@CodeBleu can you try with latest tofu or latest terraform CLI? Maybe on a different system if you suspect it’s caching related ?

**Comment by CodeBleu** [comment]
@rohityadavcloud I just tried on a fresh install ( docker container of ubuntu 22.04 ) and get the same error

This issue should prob be re-opened, correct?

```
root@48ce3dabe201:/# tofu init

Initializing the backend...

Initializing provider plugins...
- Finding cloudstack/cloudstack versions matching "0.5.0"...
- Installing cloudstack/cloudstack v0.5.0...
╷
│ Error: Failed to install provider
│
│ Error while installing cloudstack/cloudstack v0.5.0: checksum list has unexpected SHA-256 hash
│ af68c90c16b98d249ad01b9215e0dbcb66cb9de21cb3f977cc73b78d80a90413 (expected
│ 34ace84ac91a9fac1deb1d9ecef12d9478e3b46fd925f6df6811577964cbfcfe)
```

**Comment by rohityadavcloud** [comment]
Hi @CodeBleu sure feel free to re-open the issue. Can you try the same with terraform, in a docker container or a new VM?

**Comment by CodeBleu** [comment]
@rohityadavcloud I do not have the permissions to re-open the issue.
CC: @kiranchavala 

I believe I know what the issue is now. Tofu registry just directly goes to the Github repo releases and runs a pipeline to add it to the Tofu registry.  This is based off of the SHA SUM files being there and the actual release files.  The reason the  checksums don't match is because you all have updated your provider, but didn't change the version number.  I ran into this same issue when updating my provider with Tofu registry.  Their process (currently) relies on verifying the version number and if it didn't change, it wont update what is listed [here](https://github.com/opentofu/registry/blob/7e4023585a04613a12dd150cec45e114788db02b/providers/c/cloudstack/cloudstack.json#L8).  

As you can see the checksums are not matching what is in the current github repo for your provider.

From Github repo
```
496b0afdc74e216686ad755ff009396476ee84751366e934c60af8d81f98f411  terraform-provider-cloudstack_0.5.0_darwin_amd64.zip
728e99dc5e9d8baec66a3e208e848bacf3134e6f77665fbf9973e186b8f9bf9b  terraform-provider-cloudstack_0.5.0_darwin_arm64.zip
c94c7da0cb28036d5d20b4e047828c9b18fdd6b9e7ec8653f4309795c9f3b645  terraform-provider-cloudstack_0.5.0_freebsd_386.zip
052651013b6f4d7329eff9b320dc4b7c6ccc3b7279a0574e84a851407246a22e  terraform-provider-cloudstack_0.5.0_freebsd_amd64.zip
f079807153210dfa73e8d24f2e6c199d46ea6803dee4517eb625a9d0150b7a08  terraform-provider-cloudstack_0.5.0_freebsd_arm.zip
7eaeb6158bc8207ee927f81e5576d6be640d6ed02185a4a2f50836cd1f453118  terraform-provider-cloudstack_0.5.0_freebsd_arm64.zip
073d27d9e1224605af7676331a816e94a6dcf7d64e18d0759e6a47d0ba7a601f  terraform-provider-cloudstack_0.5.0_linux_386.zip
af68c90c16b98d249ad01b9215e0dbcb66cb9de21cb3f977cc73b78d80a90413  terraform-provider-cloudstack_0.5.0_linux_amd64.zip
dc5bba10bf168c1e1ee97f7ea083b4f692dfb04a501bded224ae1a28b63dcc9e  terraform-provider-cloudstack_0.5.0_linux_arm.zip
daecd1d1ab2fe19425b466f572165943f55b1f1c9bc24d17245d4c0f79fc7894  terraform-provider-cloudstack_0.5.0_linux_arm64.zip
dcbc919a4c7d786900e6e1acf5a7915c7cc87a4fae986884bae782447de6938e  terraform-provider-cloudstack_0.5.0_openbsd_386.zip
4a9e038a5c500219dd2126e63ee66359ec717809d762932e8c4f5b00efe10181  terraform-provider-cloudstack_0.5.0_openbsd_amd64.zip
a57d4c364e127a9ba41865b4a69b97d61dff02e05b9d1f3b4e6a4ea38c52d010  terraform-provider-cloudstack_0.5.0_windows_386.zip
cfe7f391919b678196293f64e1374db326ca6b03f568a0a4ad0b315f385f3590  terraform-provider-cloudstack_0.5.0_windows_amd64.zip
62051d4c32f7e6d5d95de33829a14e1ab58acf6419f7ae5912dd8e4bd9c29e57  terraform-provider-cloudstack_0.5.0_windows_arm.zip
72115237419abf5565ed15f2286d590c4fea8b2563d69d265133c488c42b6066  terraform-provider-cloudstack_0.5.0_windows_arm64.zip

```

Example of just one of the release artifacts checksum shown in the Tofu Registry:
```
 {
          "os": "linux",
          "arch": "amd64",
          "filename": "terraform-provider-cloudstack_0.5.0_linux_amd64.zip",
          "download_url": "https://github.com/cloudstack/terraform-provider-cloudstack/releases/download/v0.5.0/terraform-provider-cloudstack_0.5.0_linux_amd64.zip",
          "shasum": "34ace84ac91a9fac1deb1d9ecef12d9478e3b46fd925f6df6811577964cbfcfe"
        },
```

See [this](https://github.com/opentofu/registry/pull/277) as reference for when I went through this.

Also here are some comments from OpenTofu Slack channel I had
![image](https://github.com/apache/cloudstack-terraform-provider/assets/400979/c73f3cc5-3cb9-441b-96e9-64dc3373465e)



![image](https://github.com/apache/cloudstack-terraform-provider/assets/400979/c98fc0ac-815c-40a8-b875-10bab72ac42f)

To resolve this issue:

- Make a request in the OpenTofu Slack channel, with hopes that they will do the process where they create a commit to remove [this](https://github.com/opentofu/registry/blob/7e4023585a04613a12dd150cec45e114788db02b/providers/c/cloudstack/cloudstack.json#L8), so their pipeline process will pick up the new checksums.  :crossed_fingers: 
- Bump the provider version

**Comment by rohityadavcloud** [comment]
New provider version may need a whole new community release process. I think Tofu should fix the issue on their end as Terraform users aren’t affected.

**Comment by rohityadavcloud** [comment]
@CodeBleu I don’t know the process for Tofu but could you raise with Tofu’s registry or respective project/team?

**Comment by CodeBleu** [comment]
I messaged the same person I worked with before and gave him links to this issue.

**Comment by CodeBleu** [comment]
> New provider version may need a whole new community release process. I think Tofu should fix the issue on their end as Terraform users aren’t affected.

Is that an accurate statement?  I thought you had to open ticket with Terraform Registry? Maybe they had to change their back end commit as well, so that it would pick up your changes to provider that was still using same version.

The issue is not with new versions, the issue is when you update the release artifacts and SHAs in the repo, but do not change the version.

I can see it from both sides.  Would be nice for both registries to just work with changing files, but not versions.  At the same time it does make sense that if something changed in the release artifacts that it would make sense to bump the patch version.

**Comment by weizhouapache** [comment]
> Is that an accurate statement? I thought you had to open ticket with Terraform Registry? Maybe they had to change their back end commit as well, so that it would pick up your changes to provider that was still using same version.

AFAIK, the terraform registry have been updated.
anyone (you/we/others) can create a pull request to fix the SHA values in tofu registry (https://github.com/opentofu/registry/blob/7e4023585a04613a12dd150cec45e114788db02b/providers/c/cloudstack/cloudstack.json as you mentioned)
https://github.com/opentofu/registry/pulls
this could be easiest way

**Comment by CodeBleu** [comment]
> > Is that an accurate statement? I thought you had to open ticket with Terraform Registry? Maybe they had to change their back end commit as well, so that it would pick up your changes to provider that was still using same version.
> 
> AFAIK, the terraform registry have been updated. anyone (you/we/others) can create a pull request to fix the SHA values in tofu registry (https://github.com/opentofu/registry/blob/7e4023585a04613a12dd150cec45e114788db02b/providers/c/cloudstack/cloudstack.json as you mentioned) https://github.com/opentofu/registry/pulls this could be easiest way

@weizhouapache As I mentioned [here](https://github.com/apache/cloudstack-terraform-provider/issues/109#issuecomment-2067660251) in my previous experience, they have have recommended "going forward" to bump the version, but feel free to try and create a PR for them.  I have personally asked them twice before and that is why I got the "going forward" statement from them.  I have messaged them in their Slack channel with this issue and if they feel like doing it again or approving someone else's PR, then I say go for it, but I do not feel comfortable asking them again at this point.

Also, it doesn't make sense to me that literally anyone can submit a PR change for a repo they don't maintain.  So, even more reason for a maintainer of this repo to make a request to them.

If there is some actual small changes with this provider that can benefit the community and do a minor patch version update to 0.5.1 then we all win!

I'm not sure how soon this issue is going to go away, especially if provider owners are changing  their release files without actually bumping the version, but I would assume that now the issue is known here, that when the future releases are published, that the proper files will just be part of CI/CD or release script so that things will just work going forward.

**Comment by rohityadavcloud** [comment]
> > New provider version may need a whole new community release process. I think Tofu should fix the issue on their end as Terraform users aren’t affected.
> 
> Is that an accurate statement? I thought you had to open ticket with Terraform Registry? Maybe they had to change their back end commit as well, so that it would pick up your changes to provider that was still using same version.

To be clear, this is the CloudStack Terraform provider version, that needs to have a new RC put for vote and only then we can publish a new git tag. The issue we had was that our release manager published a git tag and deleted it, and later when it was created again Terraform registry failed to pick the new artefacts (here the version was still v0.5.0 but the publish/republish messed up the registry checksums/sha, which is supposedly immutable). To fix this the Terraform registry support first deleted the release at their end, and we had to delete/republish the tag+artifacts again using goreleaser.

> The issue is not with new versions, the issue is when you update the release artifacts and SHAs in the repo, but do not change the version.

I suppose the same thing has happened with Tofu, they need to delete old checksum/sha for their registry to re-registry the new tag+artifacts?

> I can see it from both sides. Would be nice for both registries to just work with changing files, but not versions.

Agree - registries should treat Github as source of truth, or at least some tools for valid authors/admins to delete/republish the same versions.

**Comment by CodeBleu** [comment]
@rohityadavcloud Yes, this is the case:
`I suppose the same thing has happened with Tofu, they need to delete old checksum/sha for their registry to re-registry the new tag+artifacts?`

That is why I said: `The issue is not with new versions, the issue is when you update the release artifacts and SHAs in the repo, but do not change the version.` This appears to apply to both Terraform and Tofu registry.

This is also why I mentioned this: `If there is some actual small changes with this provider that can benefit the community and do a minor patch version update to 0.5.1 then we all win!`

So the question is, which one is quicker?

1. Your version bump with this ->  `"...that needs to have a new RC put for vote and only then we can publish a new git tag."` 
2. PR and merge with Tofu?

If you choose 1, I think you or another maintainer of this repo should try creating a PR deleting [this](https://github.com/opentofu/registry/blob/7e4023585a04613a12dd150cec45e114788db02b/providers/c/cloudstack/cloudstack.json), and hopefully they can approve and merge it quickly.  If not, then the Tofu users are going to have to wait until you all release another version :crying_cat_face:  :wink:

**Comment by rohityadavcloud** [comment]
#2 I think @CodeBleu

**Comment by rohityadavcloud** [comment]
I've raised this PR - https://github.com/opentofu/registry/pull/409 let's see if they accept it, perhaps a refetch fixes your issue @CodeBleu

**Comment by rohityadavcloud** [comment]
@CodeBleu the PR https://github.com/opentofu/registry/pull/409 has been merged, once the registry pulls automatically could you advise if the issue is finally resolved for you.

**Comment by CodeBleu** [comment]
@rohityadavcloud It is now installing without checksum issue. Thanks!.

```
- Installing cloudstack/cloudstack v0.5.0...
- Installed cloudstack/cloudstack v0.5.0. Signature validation was skipped due to the registry not containing GPG keys for this provider

Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://opentofu.org/docs/cli/plugins/signing/

OpenTofu has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

OpenTofu has been successfully initialized!

You may now begin working with OpenTofu. Try running "tofu plan" to see
any changes that are required for your infrastructure. All OpenTofu commands
should now work.

If you ever set or change modules or backend configuration for OpenTofu,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```


The only thing left is to add your GPG key to OpenTofu registry so that it will pass the Signature validation.

[Here](https://github.com/opentofu/registry/pull/239) is an example from when I did this with the provider I created.


[Here](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+) is the actual link to submit it

**Comment by rohityadavcloud** [comment]
Done here https://github.com/opentofu/registry/pull/416

closing on your comment @CodeBleu

**Comment by CodeBleu** [comment]
@rohityadavcloud 
Unfortunately the signature validation is still not working:
`- Installed cloudstack/cloudstack v0.5.0. Signature validation was skipped due to the registry not containing GPG keys for this provider`

I downloaded your public key and did a quick test, and get the following:
```
 $ gpg --keyring ./tempkeyring.gpg --verify ~/Downloads/cloudstack-terraform-provider_0.5.0_SHA256SUMS.sig cs_pub_key.asc
gpg: Signature made Tue 09 Apr 2024 03:23:08 AM EDT
gpg:                using RSA key 5ED1E1122DC5E8A4A45112C2484248210EE3D884
gpg: BAD signature from "Rohit Yadav (CODE SIGNING KEY) <bhaisaab@apache.org>" [unknown]
```

Is [this](https://github.com/opentofu/registry/pull/416/files) key the same key that was used to sign the SHA file?

Maybe the SHA256SUMS file was updated when all the checksum stuff was being fixed, and the SHA256SUMS.sig just needs to be re-created/sign the SHA256SUMS file after those changes?

**Comment by rohityadavcloud** [comment]
My key is correct @CodeBleu not sure why it skipped checking signature.

**Comment by btzq** [comment]
Has this been resolved?

**Comment by rohityadavcloud** [comment]
Yes @btzq
